name       : gzdoom
version    : 4.10.0
release    : 43
homepage   : https://zdoom.org
source     :
    - https://github.com/ZDoom/gzdoom/archive/refs/tags/g4.10.0.tar.gz : 8702522c05048dfd4a765c6ac82a270d8bd0942e813d5bc6f4b69795a5d23a20
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : games.action
summary    : A port of id Software's original Linux Doom source code to Win32 and Linux
description: |
    A port of id Software's original Linux Doom source code to Win32 and Linux
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libjpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vpx)
    - bzip2-devel
    - zmusic-devel
setup      : |
    %cmake_ninja \
        -DDYN_GTK=OFF \
        -DDYN_OPENAL=OFF \
        -DINSTALL_PK3_PATH=share/doom \
        -DINSTALL_SOUNDFONT_PATH=share/doom
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 src/posix/zdoom.xpm $installdir/usr/share/pixmaps/gzdoom.xpm
    install -Dm00644 $pkgfiles/gzdoom.desktop $installdir/usr/share/applications/gzdoom.desktop

    rm -v $installdir/usr/share/doc/gzdoom/licenses/*
    rmdir $installdir/usr/share/doc/gzdoom/licenses
