name       : gzdoom
version    : 4.4.2
release    : 31
homepage   : https://zdoom.org
source     :
    - https://github.com/coelckers/gzdoom/archive/g4.4.2.tar.gz : d0ede9aefa8834b6d97a8a5336e57077475f43c297447f75b37550ee93010674
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : games.action
summary    : A port of id Software's original Linux Doom source code to Win32 and Linux
description: |
    A port of id Software's original Linux Doom source code to Win32 and Linux
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libjpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - bzip2-devel
    - zmusic-devel
setup      : |
    %cmake_ninja \
        -DDYN_GTK=OFF \
        -DDYN_OPENAL=OFF \
        -DINSTALL_PK3_PATH=share/doom
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 src/posix/zdoom.xpm $installdir/usr/share/pixmaps/gzdoom.xpm
    install -Dm00644 $pkgfiles/gzdoom.desktop $installdir/usr/share/applications/gzdoom.desktop
    install -dm00644 $installdir/usr/share/doom/{fm_banks,soundfonts}/
    install -Dm00644 fm_banks/* $installdir/usr/share/doom/fm_banks/
    install -Dm00644 soundfont/* $installdir/usr/share/doom/soundfonts/

    rm -v $installdir/usr/share/doc/gzdoom/licenses/*
    rmdir $installdir/usr/share/doc/gzdoom/licenses
