name       : gzdoom
version    : 3.2.5
release    : 5
source     :
    - https://github.com/coelckers/gzdoom/archive/g3.2.5.tar.gz : e9cf0aa5b7ee0b165532dee55e4965f6aabf1acadb79f7372f8e362540206748
license    :
    - BSD-3-Clause
    - LGPL-3.0
    - MIT
component  : games.action
summary    : A port of id Software's original Linux Doom source code to Win32 and Linux
description: |
    A port of id Software's original Linux Doom source code to Win32 and Linux
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - imagemagick
    - wildmidi-devel
rundeps    :
    - fluidsynth
setup      : |
    %cmake .
build      : |
    %make
install    : |
    install -d $installdir/usr/share/gzdoom
    cp *.pk3 $installdir/usr/share/gzdoom
    chmod -R 00644 $installdir/usr/share/gzdoom
    install -m 00755 gzdoom $installdir/usr/share/gzdoom/gzdoom
    install -d $installdir/usr/share/pixmaps
    convert 'src/win32/icon1.ico[2]' $installdir/usr/share/pixmaps/gzdoom.png
    install -D -m 00644 $pkgfiles/gzdoom.desktop $installdir/usr/share/applications/gzdoom.desktop
    install -D -m 00755 $pkgfiles/gzdoom $installdir/usr/bin/gzdoom
