name       : gzdoom
version    : 2.3.2
release    : 2
source     :
    - https://github.com/coelckers/gzdoom/archive/g2.3.2.tar.gz : 42b0e0aef90b1779a09d272b49f412ed559ce2a11dd9146f52d140bb42a8f8d0
license    :
    - BSD-3-Clause
    - LGPL-3.0
    - MIT
component  : games.action
summary    : A port of id Software's original Linux Doom source code to Win32 and Linux
description: |
    A port of id Software's original Linux Doom source code to Win32 and Linux
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - imagemagick
    - wildmidi-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    install -d $installdir/usr/share/gzdoom
    cp *.pk3 $installdir/usr/share/gzdoom
    chmod -R 00644 $installdir/usr/share/gzdoom
    install -m 00755 gzdoom $installdir/usr/share/gzdoom/gzdoom
    install -d $installdir/usr/share/pixmaps
    convert 'src/win32/icon1.ico[2]' $installdir/usr/share/pixmaps/gzdoom.png
    install -D -m 00644 $pkgfiles/gzdoom.desktop $installdir/usr/share/applications/gzdoom.desktop
