name       : gzdoom
version    : 4.0.0
release    : 13
source     :
    - git|https://github.com/coelckers/gzdoom.git : g4.0.0
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
    - MIT
component  : games.action
summary    : A port of id Software's original Linux Doom source code to Win32 and
    Linux
description: |
    A port of id Software's original Linux Doom source code to Win32 and Linux
builddeps  :
    - pkgconfig(fluidsynth)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libjpeg)
    - pkgconfig(libmpg123)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - bzip2-devel
    - imagemagick
rundeps    :
    - fluidsynth
setup      : |
    %cmake_ninja \
        -DDYN_GTK=OFF \
        -DDYN_MPG123=OFF \
        -DDYN_OPENAL=OFF \
        -DDYN_SNDFILE=OFF
build      : |
    %ninja_build
install    : |
    install -d $installdir/usr/share/gzdoom
    install -m00644 solusBuildDir/*.pk3 $installdir/usr/share/gzdoom
    install -m00644 soundfont/gzdoom.sf2 $installdir/usr/share/gzdoom/gzdoom.sf2
    chmod -R 00644 $installdir/usr/share/gzdoom
    install -m00755 solusBuildDir/gzdoom $installdir/usr/share/gzdoom/gzdoom
    install -d $installdir/usr/share/pixmaps
    convert 'src/win32/icon1.ico[8]' $installdir/usr/share/pixmaps/gzdoom.png
    install -Dm00644 $pkgfiles/gzdoom.desktop $installdir/usr/share/applications/gzdoom.desktop
    install -d $installdir/usr/bin/
    ln -s /usr/share/gzdoom/gzdoom $installdir/usr/bin/gzdoom
