name       : gzdoom
version    : 3.5.1
release    : 7
source     :
    - https://github.com/coelckers/gzdoom/archive/g3.5.1.tar.gz : 6189ac5328a835b28246c0a7a7449f8cb7f71a4f2c9868ff5315a2f598849096
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
    - MIT
component  : games.action
summary    : A port of id Software's original Linux Doom source code to Win32 and Linux
description: |
    A port of id Software's original Linux Doom source code to Win32 and Linux
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libjpeg)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - bzip2-devel
    - imagemagick
    - wildmidi-devel
rundeps    :
    - fluidsynth
setup      : |
    %cmake .
build      : |
    %make
install    : |
    install -d $installdir/usr/share/gzdoom
    cp *.pk3 $installdir/usr/share/gzdoom
    chmod -R 00644 $installdir/usr/share/gzdoom
    install -m00755 gzdoom $installdir/usr/share/gzdoom/gzdoom
    install -d $installdir/usr/share/pixmaps
    convert 'src/win32/icon1.ico[2]' $installdir/usr/share/pixmaps/gzdoom.png
    install -Dm00644 $pkgfiles/gzdoom.desktop $installdir/usr/share/applications/gzdoom.desktop
    install -d $installdir/usr/bin/
    ln -s /usr/share/gzdoom/gzdoom $installdir/usr/bin/gzdoom
