name       : gzdoom
version    : 4.1.3
release    : 19
homepage   : https://zdoom.org
source     :
    - git|https://github.com/coelckers/gzdoom.git : g4.1.3
license    :
    - BSD-3-Clause
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
    - MIT
component  : games.action
summary    : A port of id Software's original Linux Doom source code to Win32 and Linux
description: |
    A port of id Software's original Linux Doom source code to Win32 and Linux
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libjpeg)
    - pkgconfig(libmpg123)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - bzip2-devel
setup      : |
    %cmake_ninja \
        -DDYN_GTK=OFF \
        -DDYN_MPG123=OFF \
        -DDYN_OPENAL=OFF \
        -DDYN_SNDFILE=OFF \
        -DINSTALL_PK3_PATH=share/doom
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 src/posix/zdoom.xpm $installdir/usr/share/pixmaps/gzdoom.xpm
    install -Dm00644 $pkgfiles/gzdoom.desktop $installdir/usr/share/applications/gzdoom.desktop

    rm -v $installdir/usr/share/doc/gzdoom/licenses/*
    rmdir $installdir/usr/share/doc/gzdoom/licenses
